services:
  vk2tg:
    build: .
    image: vk_to_tg_poster:dev
    container_name: vk_to_tg_poster_dev
    restart: unless-stopped
    ports:
      - "${PORT:-8222}:8222"
    environment:
      TZ: ${TZ:-Europe/Moscow}
      VK_API_TOKEN: ${VK_API_TOKEN:-}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-}
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./data:/app/data
